const ActionTypes = {
  REST_LOADING: 'REST_LOADING',
  REST_SUCCESS: 'REST_SUCCESS',
  REST_ERROR: 'REST_ERROR',

  CART_LOADING: 'CART_LOADING',
  CART_SUCCESS: 'CART_SUCCESS',
  CART_ERROR: 'CART_ERROR',

  ADD_TO_CART: 'ADD_TO_CART',
  UPDATE_CART: 'UPDATE_CART',
  DELETE_CART: 'DELETE_CART',
};

export default ActionTypes;
